### ISSUE TITLE
fit() can get completely stuck

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#35]
fit() can get completely stuck at

`
0%|                                                                                                                                                      | 0/1000 [00:00<?, ?it/s]
`
upon `ctrl+c` :

```
Traceback (most recent call last):
  File ".\reduce_floyds_data.py", line 348, in <module>
    onedspec_blue = calibrate_blue(science_blue, standard_blue, standard_name)
  File ".\reduce_floyds_data.py", line 267, in calibrate_blue
    blue_onedspec.fit(max_tries=1000,
  File "c:\users\cylam\git\aspired\aspired\onedspec.py", line 2506, in fit
    self.standard_wavecal.fit(max_tries=max_tries,
  File "c:\users\cylam\git\aspired\aspired\wavelengthcalibration.py", line 876, in fit
    self.spectrum1D.calibrator.fit(
  File "c:\users\cylam\git\rascal\rascal\calibrator.py", line 1892, in fit
    self._solve_candidate_ransac(
  File "c:\users\cylam\git\rascal\rascal\calibrator.py", line 862, in _solve_candidate_ransac
    y_temp = np.random.choice(y_choice)

```

**Comment by cylammarco** [comment]
changed `continue` to `break` in the hough pairs drawing solve the problem. Now, it should throw an error instead of getting stuck.
