### ISSUE TITLE
Some problem with Github Actions submitting test report to Coverall

### ISSUE THREAD

**Issue by cylammarco** [jveitchmichaelis/rascal#69]
```
Trying submitting coverage with service_name: github...
cd .
Failed submitting coverage with service_name: github
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/coveralls/api.py", line 290, in submit_report
    response.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/requests/models.py", line 953, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 4[22](https://github.com/jveitchmichaelis/rascal/runs/7999192476?check_suite_focus=true#step:9:23) Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/src/entrypoint.py", line 82, in run_coveralls
    result = coveralls.wear()
  File "/usr/local/lib/python3.10/site-packages/coveralls/api.py", line [25](https://github.com/jveitchmichaelis/rascal/runs/7999192476?check_suite_focus=true#step:9:26)7, in wear
    return self.submit_report(json_string)
  File "/usr/local/lib/python3.10/site-packages/coveralls/api.py", line [29](https://github.com/jveitchmichaelis/rascal/runs/7999192476?check_suite_focus=true#step:9:30)3, in submit_report
    raise CoverallsException(
coveralls.exception.CoverallsException: Could not submit coverage: 422 Client Error: Unprocessable Entity for url: https://coveralls.io/api/v1/jobs
cd /github/workspace
Trying submitting coverage with service_name: github-actions...
```

**Comment by cylammarco** [comment]
Fixed in https://github.com/jveitchmichaelis/rascal/commit/9524c18baf0e440abff0d36146efbaef45b6ff43
